### ISSUE TITLE
Is conda-libmamba-solver no longer needed with conda 4.13?

### ISSUE THREAD

**Issue by timsnyder-siv** [conda-forge/conda-libmamba-solver-feedstock#2]
### Comment:

A project I work on sets up conda using https://github.com/firesim/firesim/blob/382d0f83e973d9ca98c9495e5cf805be007a191b/scripts/machine-launch-script.sh, essentially doing:

```
bash install_miniforge_4.12.0.sh
conda install -n base conda-build # which now updates conda to 4.13
conda install -n base conda-libmamba-solver
```

And the install of `conda-libmamba-solver` fails with:
```
+ /opt/conda/bin/conda install -y -n base conda-libmamba-solver
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - conda==4.12.0
```

If I change the install command to `conda install -n base conda=4.12.0 conda-libmamba-solver` conda will revert itself to 4.12 and install `conda-libmamba-solver` correctly.  Likewise, I can `conda config --system --set auto_update_conda false` and conda won't update itself when installing conda-build and the install of `conda-libmamba-solver` succeeds.

Looking at the recipe for `conda-libmamba-solver` I don't understand how it is failing like I'm seeing.  I would expect it to install because the runtime requirement is `conda>=4.12.0`.

I'll work around this for now by preventing conda from updating itself.  If anyone else has other thoughts or comments, I appreciate it.

**Comment by jaimergp** [comment]
Oops, sorry @timsnyder-siv, I thought I was watching this repo but I wasn't. Are you still affected by this issue?

conda-libmamba-solver is definitely needed as a separate package if you want to opt in to use the experimental solver.

**Comment by jezdez** [comment]
I think this can be closed, conda-libmamba-solver is needed, it's a conda plugin that implements a conda solver based on libmamba.
